### ISSUE TITLE
Metric: policy server counter

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#102]
The goal of this metric is to allow an operator to understand how many policy servers are installed in the cluster.

The policy provides also some labels, that can be used to filter the metric and provide really specific data.

## Metric name

`kubewarden_policy_server_total`

## Metric type

Counter

## Use cases

* How many policy servers have been active inside of the cluster during a certain time frame

## Labels

* `name` - string: name of the policy server as registered in the PolicyServer custom resource
* `replicas` - integer: number of replicas for the policy server
* `serviceAccountName` - string: service account name that will be tied to the Policy Server deployment

**Comment by flavio** [comment]
Closing, we will reopen if there's demand from our users
