### ISSUE TITLE
Add `ServerStatus` and Conditions to PolicyServer CRD

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#109]
PolicyServer CRs now have new several fields, and those fields may be misconfigured. As a user, if I specify incorrectly a PolicyServer, currently the only way to notice is by going to the controller logs, or by seeing that deployments/pods/configmaps are not there.

Provide status info to the PolicyServer analogous to what was done for ClusterAdmissionPolicies (see the work of `PolicyStatus` in https://github.com/kubewarden/kubewarden-controller/pull/76).

## Acceptance criteria

- A new field `ServerStatus` has been added to `PolicyServerStatus` struct. It can have values: `pending, active`
- A new Conditions have been added to the `PolicyServerStatus` struct: `PolicyServerConfigmapReconciled`, which informs if the configmap associated to that policy server has been correctly reconciled.
- Check that `ServerStatus` is initialized correctly (to `pending`, for example).
- Add the status as a column when doing `kubectl get policyservers` (achieved with a `+kubebuilder:printcolumn` marker, see the policies types)
- Update docs to reflect the new functionality

**Comment by jvanz** [comment]
@viccuad believes this is not necessary anymore and said we can close this issue
