### ISSUE TITLE
Provide default PolicyServer image tag from the controller

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#120]
Dealing with PolicyServer CRs that specify a policy-server image version that is out of sync with regards to the latest features is annoying. For example, docs.kubewarden.io may contain old examples of PolicyServer CRs, with old version tags for the policy-server image in the `spec.image` key.

### Acceptance criteria

- PolicyServer's `spec.image` is not required anymore, as the controller will provide a suitable default.
- The Controller contains a hard coded value for `spec.image`, including the tag version of the image. This value is configurable in the Controller Configmap via a `policyServerImage` key.
- If a PolicyServer CR provides a `spec.image`, it will take precedence over the one that the Controller provides. If not, the Controller will use its default `spec.image` when creating the PolicyServer resource. Hence, the value from PolicyServer CR has precedence, then the value from the Controller Configmap, and last, the hardcoded one in the Controller.
- Examples of PolicyServer CRs on docs.kubewarden.io don't use `spec.image`

**Comment by flavio** [comment]
> PolicyServer's spec.image is not required anymore, as the controller will provide a suitable default.

I think this line should be dropped, it contradicts what comes after. The PolicyServer CR will still have a way to express a custom image to be used

**Comment by ereslibre** [comment]
I think the point is to not make it required, but optional. Can be provided if desired, but is not mandatory.

**Comment by flavio** [comment]
Today we discussed about this issue inside of our planning meeting. We decided to postpone the work on it, until we have a better understanding of what our users would prefer.

So far, this is how we would attempt to solve this problem

## Possible solution

The Kubewarden Controller already owns a ConfigMap. We would write into the ConfigMap the image of Policy Server that has to be used by default. This is the version that is currently written inside of our helm chart.

The Policy Server CRD would be relaxed to make `spec.image` optional. When the user doesn't provide a value, the controller will use the value defined inside of the ConfigMap.

The helm chart is already providing an entry inside of `values.yml` to tune which version of Policy Server has to be used when deploying the `default` PolicyServer instance.
The helm chart will write this version inside of the ConfigMap used by the controller.

### How to handle updates of Policy Server

When a new version of Policy Server is released, we will update the helm chart to ensure this version is the one put into the controller's ConfigMap.

The existing Policy Server instances (both the default and the user-created ones) are not going to be upgraded. The user will have to update them manually (at least as a 1st iteration).

**Comment by flavio** [comment]
Closing, this is kinda adressed with the helm chart now.
