### ISSUE TITLE
Improve the logic to trigger a rollout when the policy-server image changes

### ISSUE THREAD

**Issue by raulcabello** [kubewarden/kubewarden-controller#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We should do a rollout of the `policy-server` Deployment if the image has changed. Currently we are checking the image for the first container [Containers[0]](https://github.com/kubewarden/kubewarden-controller/blob/30d36df36827f27a4641b37b6caa663c20bd6404/internal/pkg/admission/policy-server-deployment.go#L123)
There might be the case that our policy-server container is not always the first container. For example if some webhook adds a sidecar container. If our `policy-server` is not the first container, `policy-server` image updates won't work.

### Expected Behavior

Changes to `policy-server` image should always trigger a rollout regardless the order and number of containers in the pod

### Steps To Reproduce

1. Add an additional container in the first position to the `policy-server` deployment template spec  
2. Change  `policy-server` image
3. No rollout happens

### Environment

```markdown
All
```

**Comment by jvanz** [comment]
@raulcabello how did you simulate this issue? I've tried to follow your reproduce steps, but I could not see the issue. I've used k9s to add a new container in the policy server deployments, then still using the k9s, changed the policy server container image. But the controller triggered a rollout. Actually, it removed the container that I added manually in the process. 

Am I missing something?
