### ISSUE TITLE
Automatically publish yaml files under `config` in the Helm charts

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#198]
When we change some configuration in the controller, kubebuilder will updates the yaml files necessary to run the controller. Like the RBAC under `config/rbac`. It would be nice to have an automation to copy and edit (if necessary) these files into the [helm chart repository](https://github.com/kubewarden/helm-charts).

**Comment by viccuad** [comment]
I look forward to this too!
For the crds, one needs to run `make generate-crds` and consume the `./generate-crds` folder. I side with adding a more general target that puts things in a specific folder, and then another target in helm-charts that consume it.

**Comment by flavio** [comment]
Closing, we will discuss it again when we agree about the versioning strategy
