### ISSUE TITLE
Provide Software Bill Of Materials

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#228]
We should generate a SBOM for the kubewarden controller.

Requirements:

  * [x] Each controller release has its own SBOM file generated
  * [x] The SBOM is signed using cosign
  * [x] The SBOM is attached to the GH Release as an artifact

**Comment by flavio** [comment]
I would suggest to use https://github.com/kubernetes-sigs/bom - this is what the Kubernetes release teams relies on

**Comment by jvanz** [comment]
Bringing this to the board because we need this info in the self-assessment document. https://github.com/kubewarden/kubewarden.io/issues/93
