### ISSUE TITLE
AKS: {"error": "leader election lost"}

### ISSUE THREAD

**Issue by floriankoch** [kubewarden/kubewarden-controller#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The kubewarden-controller exists with this error:

`E0526 17:09:12.948571       1 leaderelection.go:367] Failed to update lock: Put "https://172.16.0.1:443/apis/coordination.k8s.io/v1/namespaces/kubewarden/leases/a4ddbf36.kubewarden.io": context deadline exceeded
I0526 17:09:12.948730       1 leaderelection.go:283] failed to renew lease kubewarden/a4ddbf36.kubewarden.io: timed out waiting for the condition
1.6535849529487903e+09  DEBUG   events  Normal  {"object": {"kind":"ConfigMap","namespace":"kubewarden","name":"a4ddbf36.kubewarden.io","uid":"3e9e8674-e803-455f-b295-5e7d4db35839","apiVersion":"v1","resourceVersion":"440640878"}, "reason": "LeaderElection", "message": "kubewarden-controller-57b7658b48-2brkx_c982fed9-3ee7-4f76-8434-9fd340151e90 stopped leading"}
1.653584952948952e+09   DEBUG   events  Normal  {"object": {"kind":"Lease","namespace":"kubewarden","name":"a4ddbf36.kubewarden.io","uid":"cc4d7796-e552-4d19-8b92-0c1f8ae293e8","apiVersion":"coordination.k8s.io/v1","resourceVersion":"440640848"}, "reason": "LeaderElection", "message": "kubewarden-controller-57b7658b48-2brkx_c982fed9-3ee7-4f76-8434-9fd340151e90 stopped leading"}
1.6535849529489608e+09  INFO    Stopping and waiting for non leader election runnables
1.653584952949005e+09   INFO    Stopping and waiting for leader election runnables
1.653584952948793e+09   ERROR   setup   problem running manager {"error": "leader election lost"}`

@flavio @ereslibre 
I think this is the root cause for https://github.com/kubewarden/policy-server/issues/239

The kubewarden-controller is restartet and works again  (thanks to readiness & liveness)

Maybe this is only an Issue on AKS? I can not see the Controlplane for my AKS Clusters , so i have no idea  how its build and what happend

### Environment

```markdown
AKS Cluster 1.21.9
```

**Comment by flavio** [comment]
We can close this issue, the https://github.com/kubewarden/policy-server/issues/239 issue has been fixed with kubewarden 1.0.0 release and it was not due to leader elections.

The leader election message is just to be considered as an information, it's not an error per se.
