### ISSUE TITLE
Research: determine steps required to upgrade our CRDs

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#240]
We want to upgrade our CRDs from alpha to either beta or v1.

The purpose of this card is to research what are the steps required to bump our current CRDs to a new maturity level. Users with alpha resources should still be able to operate their clusters and should not lose their already defined resources.

## Acceptance criteria

* [x] determine the list of actions that have to be performed
* [x] have a rough estimation about the time required by each operation that has to be done
* [x] ensure no data loss is caused by users

**Comment by flavio** [comment]
@raulcabello can you estimate how hard would it be to implement the conversion?

**Comment by raulcabello** [comment]
@flavio I don't believe it will take long around two days (or even less than that)

Closing this since we just agreed to go for v1 and keep v1alpha2 with the conversion https://github.com/kubewarden/kubewarden-controller/issues/245 . Feel free to reopen if you still want to discuss this.
