### ISSUE TITLE
Add Trivy scan in CI pipeline

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#244]
Recently we had an issue where [Artifacthub shown a security issue to be solved in out controller](https://github.com/kubewarden/kubewarden-controller/issues/235). Even if the report was not valid due a bug in the Artifacthub side, I think we need to check our binaries before publishing them.As well as before merging PRs.  For that, we can add a step in our CI to run Trivy. Which is the same scanner used by Artifacthub. There is a [github action](https://github.com/aquasecurity/trivy-action) available for that.

**Comment by viccuad** [comment]
Closing, we are consuming the security scans from Artifacthub instead.
