### ISSUE TITLE
High security issues reported by Artifacthub

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#265]
The artifacthub page for the [kubewarden-controller](https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller) show 5 security issues. Two of them with high severity. We should address these issues as soon as possible.

**Comment by jvanz** [comment]
This issue remember this another open task: https://github.com/kubewarden/kubewarden-controller/issues/244

Maybe we can take this opportunity to also add this step in our CI to help us detect this kind of problem.

**Comment by viccuad** [comment]
Reopening, until the new image is tagged and released. I will test `main` first
