### ISSUE TITLE
Check if Kuberwarden has a equivalent policy to Neuvector policy to control user used in the containers.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#308]
Compare the admission controller from Neuvector checking how its policy to control container user works. The goal if to figure out if Kubewarden policy is equivalent against it.

**Comment by jvanz** [comment]
As far as I can see we can replace this rule with our policy [user-group-psp-policy](https://github.com/kubewarden/user-group-psp-policy). It also checks the user in containers. By the way, our policy check more  things. As we can see in the [`neuvector/controller/rest/admwebhook.go`](https://github.com/neuvector/neuvector/blob/4c48aa987801490bb9dcdb17d325ae7c93898daa/controller/rest/admwebhook.go#L269) file Neuvector get the user from the [container or pod spec](https://github.com/neuvector/neuvector/blob/4c48aa987801490bb9dcdb17d325ae7c93898daa/controller/rest/admwebhook.go#L399-L404) (container has precedence). But it does not check init containers. Our policy does.

**Comment by jvanz** [comment]
Ah! One thing that our policy does not does is to check the PodSec security context. Our policy only checks the containers security context.

**Comment by jvanz** [comment]
https://github.com/kubewarden/user-group-psp-policy/issues/36

**Comment by flavio** [comment]
Let's close this issue and track that via https://github.com/kubewarden/user-group-psp-policy/issues/36
