### ISSUE TITLE
Check if Kuberwarden has a equivalent policy to Neuvector policy to control user groups

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#309]
Compare the admission controller from Neuvector checking how its policy to control  user groups works. The goal if to figure out if there is a Kubewarden policy equivalent to it.

**Comment by jvanz** [comment]
The rule from NueVector that refers to "user group" check which [user group from the user info in ](https://github.com/neuvector/neuvector/blob/4c48aa987801490bb9dcdb17d325ae7c93898daa/controller/rest/admwebhook.go#L506-L513) [the admission request](https://github.com/neuvector/neuvector/blob/4c48aa987801490bb9dcdb17d325ae7c93898daa/controller/cache/admission.go#L1226-L1231). It's not related to the user group in the containers. Therefore, if we want a feature like that, we need to write a policy to do the same thing.

**Comment by flavio** [comment]
I suspected that was about the user and group info inside of the admission request object. Can you please elaborate more how the final policy would behave?

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers , I cannot think an a big benefit in adding a policy similar to the Neuvector one in the Kubewarden ecosystem  now. So, I'm closing this. 

However, if we decided to do it, it's possible. Our SDK already has the [data needed](https://github.com/kubewarden/policy-sdk-rust/blob/11664f94ff753f2f05110e98640877a10249e62d/src/request.rs#L86)
