### ISSUE TITLE
Provide instructions to migrate ClusterAdmissionPolicy from v1alpha1 to v1alpha2

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#34]
Our next release notes must include instructions explaining how to migrate `ClusterAdmissionPolicy` from `v1alpha1` to `v1alpha2`.

No automated migration is going to be performed by us. The users will have to perform some manual steps.

**Comment by flavio** [comment]
Draft of release notes can be found here: https://gist.github.com/flavio/46d49537fbb85571560fa90fe31f65eb

**Comment by flavio** [comment]
@ereslibre can you take a look look at the proposed release notes, please?

**Comment by ereslibre** [comment]
Is there a PR-like changeset I can review? I have some comments

**Comment by flavio** [comment]
> Is there a PR-like changeset I can review? I have some comments

Here you go: https://github.com/kubewarden/kubewarden-controller/pull/36
