### ISSUE TITLE
100% Security Score - sign up for CNCF Security Slam to get the rewards! 

### ISSUE THREAD

**Issue by Salkimmich** [kubewarden/kubewarden-controller#347]
Hey Kubewarden team,

It looks like from the CLO Monitor that you've gotten to 100% security compliance with OSSF! 

It doesn't look like you have signed up for the CNCF Security Slam yet - if any maintainter/contributer signs up this project within the next week we'll be able to get some awards out to your community and dedicate $2,500 to the CNCF Diversity Scholarship in Kubewarden's name! 

https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam

Thanks for making open source a little more secure !

**Comment by flavio** [comment]
@Salkimmich thanks a lot for reaching out! We didn't know about this event.

I've just signed up as a maintainer for the Kubewarden project :partying_face: 

I'm closing this issue as resolved, please re-open/comment on it if there's anything else we can do.

Thanks again!

**Comment by Salkimmich** [comment]
Awesome - glad we could count you in for your perfect score!
