### ISSUE TITLE
Community meeting improvements

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#380]
@divya-mohan0209's feedback on slack:

* [ ] Create a googlegroup for Kubewarden with the official kubewarden SUSE ID.
* [ ] Have a monthly calendar entry created against the calendar for the googlegroup.
* [ ] Enter the designated zoom link on the calendar entry.
* [ ] Ask folks to join that google group on our #kubewarden channel in the K8s Slack.

What this would do is:
* Give people an official mailing list via the googlegroup
* We can schedule any community-facing events around Kubewarden like a release-cut/global online meetup on this group.

**Comment by viccuad** [comment]
From daily:
- Reconsider monthly calendar as they are bound to Google account
- Ask Robert where the recordings can be shared.

**Comment by olblak** [comment]
Quick update on my calendar experimentation>
* Using Hugo, I tried doing steps described on https://discourse.gohugo.io/t/calendar-ics-template/7137 I couldn't finish it 
* Using [Fruux](https://fruux.com/), it's really easy to use but I coudln't embed the calendar on Kubewarden.io website
* Using [TeamUP](https://www.teamup.com/), I didn't try it yet but sounds promising

**Comment by jvanz** [comment]
@flavio created an calendar in TeamUP and updated kubewarden.io adding the calendar feed in the home page. Therefore, I'm closing this issue.
