### ISSUE TITLE
Kubewarden cannot be removed when installed with Fleet

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Kubewarden stack is installed using `GitRepo` from fleet the users are not able to remove it. It seems this is caused by the order used in the removal process. Fleet seems to remove the CRDs before the other Helm charts. Therefore, the [pre-delete-hook](https://github.com/kubewarden/helm-charts/blob/29a6265e81142a2bdfba8419fdbe8ededa2e5d07/charts/kubewarden-controller/templates/pre-delete-hook.yaml) fails and the controller cannot be removed. 
 
This is an [repository](https://github.com/kubewarden/fleet-example) with an example that can be used to simulate the issue.

### Expected Behavior

The Kubewarden stack should be removed with no issues

### Steps To Reproduce

1. Create a Kubernetes cluster
```console
minikube start --kubernetes-version=v1.20.15
```
2. Install cert-manager
```console
kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
kubectl wait --for=condition=Available deployment --timeout=2m -n cert-manager --all
```
3. Install Kubewarden stack using the example repository
```console
cat > example.yaml << "EOF"
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kubewarden-example
  namespace: fleet-local
spec:
  repo: https://github.com/kubewarden/kubewarden-fleet
  branch: main
  paths:
  - helm-kubewarden/
EOF

kubectl apply -f example.yaml
```
4. Remove the GitRepo object installed in step 3
```console
kubectl delete -f example.yaml
```
5. Check the errors in the pods deployed

### Environment

```markdown
- OS:
- Architecture:
```

### Anything else?

We should check if there is something from the Kubewarden side where we can mitigate the issue. If there is nothing that the Kubewarden team can do, we should contact the Fleet project and report the problem.

**Comment by flavio** [comment]
@jvanz please, reach out to @mattfarina to understand if there's a solution for that. This problem happens also when Kubewarden is installed via helm, and the user removes by mistake the CRD chart first (which happens when the whole kubewarden stack is uninstallalled via Rancher Manager)

**Comment by viccuad** [comment]
(just in case, we document [2 workarounds in docs.kubewarden.io](https://docs.kubewarden.io/operator-manual/Rancher-Fleet), either staggering the removal changes to the git repo, or using a separate Fleet GitRepo for the CRD chart).

**Comment by jvanz** [comment]
> (just in case, we document [2 workarounds in docs.kubewarden.io](https://docs.kubewarden.io/operator-manual/Rancher-Fleet), either staggering the removal changes to the git repo, or using a separate Fleet GitRepo for the CRD chart).

@kubewarden/kubewarden-developers , Is these workaround enough for us now? If so, we can clone this issue.

**Comment by flavio** [comment]
I think this is enough, what @viccuad thinks?

**Comment by jvanz** [comment]
@eumel8 @viccuad can we close this? Is the workaround  good enough for you?
