### ISSUE TITLE
Improve structured logging

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#4]
Logging should be improved and potentially structured. This can help to debug potential issues on the controller logic.

**Comment by flavio** [comment]
@ereslibre this could be tackled while working on the new architecture. Do you have something concrete in mind?

CC @raulcabello , @viccuad

**Comment by ereslibre** [comment]
I don't and I haven't done structured logging with a controller before, but I think this is something we want to pursue so we have better visibility and are able to trace behaviors with specific policies and how the controller manages resources that are somehow linked to those policies/custom resources.

**Comment by flavio** [comment]
Ok, I would close this issue because it's too generic.

Let's just keep in mind, when reviewing PR against the controller, that log messages should be done in a structured way.

CC: @raulcabello and @viccuad
