### ISSUE TITLE
Update docs & tests to registry.k8s.io from k8s.gcr.io

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#403]
k8s.gcr.io registry is being sunset and moved to registry.k8s.io.
Deadline April 3rd.

See:
https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/
[kubewarden maintainers mail-list announcement](https://lists.cncf.io/login?r=https%3A%2F%2Flists.cncf.io%2Fg%2Fcncf-kubewarden-maintainers%2Fmessage%2F27)

# Acceptance criteria

Migrate these docs and & test usages: https://github.com/search?q=org%3Akubewarden%20%22k8s.gcr.io%22&type=code

**Comment by durlabhcodes** [comment]
Can I work on it?

**Comment by viccuad** [comment]
@durlabhcodes yes, feel free to tackle it. I have assigned you then.
This issue will need of 3 simple PRs to 3 different repos.

**Comment by durlabhcodes** [comment]
Hey @viccuad Raised these PRs

https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/53
https://github.com/kubewarden/docs/pull/166
https://github.com/kubewarden/go-policy-template/pull/34

See if they look fine to you
