### ISSUE TITLE
Reach out to community policies, propose changes of github-actions@v2

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#418]
Reach out to community policies and propose consuming kubewarden/github-actions@v2 so they get up-to-date `artifacthub-pkg.yml`.

Offer to help if they want their policies published in https://artifacthub.io.

### Acceptance criteria

Open PR against community policies listed in https://github.com/topics/kubewarden-policy. Bump github-actions to v2, provide up-to-date metadata.yml and artifacthub-pkg.yml, offer to help if they want to publish on artifacthub:
- [x] [https://github.com/nlamirault/probes-policy](https://github.com/nlamirault/probes-policy/issues/10)
- [x]  [https://github.com/nlamirault/disallow-default-namespace-policy](https://github.com/nlamirault/disallow-default-namespace-policy/issues/12)

**Comment by jvanz** [comment]
I'm trying contact with the policies author. No success so far. Moving to block

**Comment by flavio** [comment]
Closing to remove clutter. This is out of our control and not blocking us
