### ISSUE TITLE
Feature Request: Create a mutating policy that can mutate any object based on configuration options

### ISSUE THREAD

**Issue by Martin-Weiss** [kubewarden/kubewarden-controller#436]
### Is your feature request related to a problem?

Whenever a new namespace is created we want to add some PSA labels, automatically in case they are missing or different.
Whenever a new POD in a given namespace is created we want to add some labels on that POD, automatically based on the namespace the POD is created in.

### Solution you'd like

A policy with some configuration options would be great.

See also https://open-policy-agent.github.io/gatekeeper/website/docs/mutation/

### Alternatives you've considered

Using OPA https://open-policy-agent.github.io/gatekeeper/website/docs/mutation/

**Comment by flavio** [comment]
Closing this issue, I've created two dedicated issues:

* https://github.com/kubewarden/kubewarden-controller/issues/451
* https://github.com/kubewarden/kubewarden-controller/issues/452

@Martin-Weiss please take a look at these new issues and provide feedback about the policies
