### ISSUE TITLE
Update all policies with new spec.backgroundAudit as needed

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#479]
The default value is spec.backgroundAudit is true, hence, we can to set it to false for the policies targeting *. Right now we don't have policies using user/group information. Add the severity and category annotations per policy.

### Acceptance criteria:

All the relevant policies are updated and a new release is done for each one of them

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers, as far as I can see, I've updated and bumped the version of all the policies. I'm moving this to "Pending review" to double check if I'm missing something. If all the PR opened covered all the policies (and they are merged) we can close this issue.

**Comment by viccuad** [comment]
merged, and tagged the last batch. Also went through all of them to recheck if the tags I pushed were correct or we missed any, and all have the correct releases.

Closing as done! Thanks José!
