### ISSUE TITLE
Move the business logic from the existing controller to the new one

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#48]
After https://github.com/kubewarden/kubewarden-controller/issues/47, an empty controller will have been created. This card should move the business logic from the previous controller into the new one.

**Acceptance criteria**

- The business logic of the existing controller is moved into the new one.
- https://github.com/kubewarden/kubewarden-controller/issues/55
- https://github.com/kubewarden/kubewarden-controller/issues/56
- https://github.com/kubewarden/kubewarden-controller/issues/57
- https://github.com/kubewarden/kubewarden-controller/issues/58
- https://github.com/kubewarden/kubewarden-controller/issues/59
- https://github.com/kubewarden/kubewarden-controller/issues/67

**Comment by flavio** [comment]
All the linked issues have been done, closing
