### ISSUE TITLE
Tag new release of kubewarden controller

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#534]
We have recently added a new validation endpoint inside of the kubewarden controller. This is used to validate PolicyServer custom resources.

The helm chart `kubewarden-controller` is registering this webhook endpoint.

We have to:
- Build a new container image of the kubewarden controller that has the new validating endpoint (v1.7.1)
- Build a new container image of the audit-scanner that consumes the controller libraries (v1.7.1)
- `kubewarden-controller` helm chart: wait for the automation to create a PR that bumps the version of the container images that is deployed
- Merge the PR
- Make a PR against `kubewarden-controller` bumping the chart version (a patch release)
- Merge the PR and wait for the automation to release a new helm chart

**Comment by viccuad** [comment]
Edited the description to include the bump of audit-scanner 1.71.
