### ISSUE TITLE
spike: consider using Tilt and Telepresence for development  

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#548]
We could consider using [Tilt](https://github.com/tilt-dev/tilt) and [Telepresence](https://github.com/telepresenceio/telepresence) for development. 
This means we could get rid of `kube-webhook-wrapper` related code, that is now needed in development mode.

Related to: https://github.com/kubewarden/kubewarden-controller/pull/541

**Comment by flavio** [comment]
The reason we're looking into these solutions is to allow a better developer experience when working on the controller. Most important, we want to remove the hackish way we expose the controller HTTPs server during the development mode.

This https server is used to serve the webhook endpoints that validate our CRDs.

To decide which solution to pick, I propose to implement the following test:

1. Create a simple web application

The application will expose one single route `/` which returns a hello world. I think the application should be written using Go using the standard libraries, like with do with the controller. Basically what is shown [here](https://pkg.go.dev/net/http#hdr-Servers).

The application will start a HTTPS server that uses a certificate and key loaded from the local filesystem.

2. Define a Kubernetes Service

The application should be exposed inside of the Kubernetes cluster using a `ClusterIP` service.

3. Access the application from the cluster

From within the cluster, start a container and try to access the application by going through the internal service.

A container with alpine + curl should just work out of the box.

The CA used to generate the application certificate can be copy-pasted into the container

4. Do changes to the local app

Change the `hello world` response to something else. Ensure the change is seen by the alpine container running inside of the cluster.

**Comment by jvanz** [comment]
It looks like to me that telepresence is the closest tool to archive what we do now manually. Which is running a local process that is accessible from the cluster workloads. And it works fine. This is a example:

Let's create a simple web server in go:

```go
package main

import (
	"fmt"
	"net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Handler here!")
	responseString := "Hello Kubewarden!"
	fmt.Fprintln(w, responseString)
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Servidor em execução na porta 8080...")
	http.ListenAndServe(":8080", nil)
}
```

Now, let's test telepresence. For that, you must have a local Kubernetes cluster and telepresence installed in your machine. Be aware that you should use the telepresence [binary](https://github.com/telepresenceio/telepresence/releases) from the github repository. The binary from the [Ambassador](https://www.getambassador.io/docs/telepresence/latest/quick-start) requires a singup in their cloud. 

Once you have all installed, create a service in the default namespace
```
kubectl create deploy hello --image=registry.k8s.io/echoserver:1.4
kubectl expose deploy hello --port 80 --target-port 8080
```

Install telepresence in the cluster:

```
telepresence helm install
```
Connect your workstation into the cluster
```
telepresence connect
```

In the host machine, reach the echo server running in the cluster
```
curl -XGET hello
```
To test inner cluster communication, try to reach the service using curl pod
```
kubectl run mycurlpod --image=curlimages/curl -i --tty -- sh
curl -XGET hello
```

Intercept inbound request to the previous created service
```
telepresence intercept hello --port 8080:80
```

Run the server in the host machine
```
go run server.go
```

In the host machine, reach the echo server running in the cluster
```
curl -XGET hello
```

To test inner cluster communication, try to reach the service using curl pod
```
kubectl run mycurlpod --image=curlimages/curl -i --tty -- sh
curl -XGET hello
```

After that, you must be able to notice that when you intercept the traffic you can run the app locally in the host machine

**Comment by jvanz** [comment]
I believe the pro for Tilt is that it actually do what the whole pipeline does. Like container build, helm chart installation and so on. It's important to notice that the container build image can be optimize (there is docs for that). Which means that we will not wait for the whole build time. 

However, I agree that telepresen is the closest what we already use and we can start by using it.

**Comment by jvanz** [comment]
Testing telepresence in the controller main branch. Moving to in progress again.
