### ISSUE TITLE
coding conventions / guidelines

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#551]
# Coding conventions

Beyond the obvious (well-tested, easy to read)
we prefer guidelines that are automatically enforced, e.g. through Rustfmt,
Clippy or the custom linter we have written.

The following are guidelines that we try to follow:
(from [buck2](https://github.com/facebook/buck2/blob/main/HACKING.md#coding-conventions)) 
- Follow standard rustfmt conventions.
- Prefer to_owned to convert &str to String.
- Qualify anyhow::Result rather than use anyhow::Result.
- Bin: Most errors should be returned as anyhow::Result. Inspecting errors outside tests and the top-level error handler is strongly discouraged.
- Lib: Use thiserror deriving enum values, avoid raw anyhow!.
- Bin/Lib: Most errors should be constructed with thiserror deriving enum values, not raw anyhow!.
- Prefer use crate::foo::bar over use super::bar or use crate::foo::_, apart from test modules which often have use super::_ at the top.
- In production-quality code, most Rustaceans choose expect rather than unwrap and give more context about why the operation is expected to always succeed. That way, if your assumptions are ever proven wrong, you have more information to use in debugging.

# Testing

- Prefer to use the assert_eq! macro over assert!(a == b) or assert!(a.eq(&b)).
- Prefer to use tests without return values over tests that return Result<(), Error>.
  This to avoid the boilerplate of writing Ok(()) in the test body and to avoid to import anyhow::Result in the test module.
- Use tabletesting with rstest for tests with similar cases but different inputs.
- Use mockall for mocking structs and traits and conditional compilation: https://github.com/oxidecomputer/omicron/blob/aceb7444938afb60f01fdf5ddeb05fd23349674d/illumos-utils/src/fstyp.rs#L33
- Use mockall_double (??? should we?)
- Avoid writing traits only for testing purposes.

- Opinionated: https://matklad.github.io/2021/05/31/how-to-test.html

**Comment by viccuad** [comment]
Looks good to me :).

**Comment by flavio** [comment]
seems reasonable to me

**Comment by jvanz** [comment]
I'm fine with the guidelines proposed. We can move forward and document that in the repository CONTRIBUTING files.
