### ISSUE TITLE
Feature request: Check `spec.rules` for plurals and small case

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#561]
When instantiating a policy, we expect resources in plurals and small case in `spec.rules`.

Add a check to the controller for this.

#### Acceptance criteria

Policies with incorrect `spec.rules`  should be rejected on instantation by the controller.

**Comment by flavio** [comment]
I think it would be a bit tricky to implement a sanitizer for that. We could rely on the results of the API that is hit by `kubectl api-resources`.
However, if we were to do that, the user would not be able to define policies targeting CR that are not yet defined on the cluster. I honestly don't know how important that would be as a use case

**Comment by viccuad** [comment]
Yes, indeed. I arrived to the same conclusion the other day, forgot to update the card.

The current approach of using `kwctl scaffold` is a better UX for users and already takes care of these issues. I'm closing the card then.
