### ISSUE TITLE
Policy to enforce pod resource limits

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#590]
We have a user that is requesting a policy to validate pod resource limits. We cannot use the [Gatekeeper policy](https://artifacthub.io/packages/gatekeeper/gatekeeper-policies/k8scontainerlimits) for that because it uses regex built-ins. Which is not implemented in the Kubewarden stack yet. Therefore, we need to write a policy to allow the user to perform these validations. This could mean two options:

1. Change the Gatekeeper policy removing the code that uses regex and build it as a Kubewarden policy
2. Write a policy from scratch to validate the resource limit

**Comment by flavio** [comment]
We could also implement the missing built-ins inside of burrego.

However, there's also this built-in Kubernetes admission controller that could achieve the same result: https://kubernetes.io/docs/concepts/policy/limit-range/

The user could rely on that while we work on one of the solutions from above

**Comment by elenagarciam** [comment]
> We could also implement the missing built-ins inside of burrego.
> 
> However, there's also this built-in Kubernetes admission controller that could achieve the same result: https://kubernetes.io/docs/concepts/policy/limit-range/
> 
> The user could rely on that while we work on one of the solutions from above

The limit range applies is too general so if we configure the same reservations to all namespaces then we come out to a great amount of reserved resources that probably are not used. The point is to enforce minimum request possible to the application which have not them configured in order drecrease the  amount of unused resources requested

**Comment by jvanz** [comment]
I'm working in the policy it will firstly checks whether the container has any resource limits defined. After that, the policy verifies that the resource limit specified in the container is within the permissible range set by the maximum limit specified in the policy settings. If the container's resource limit exceeds the predefined maximum, the policy intervenes by allowing the user to mutate the container's settings, adjusting the limit to comply with the maximum value established in the policy configuration.

**Comment by elenagarciam** [comment]
> I'm working in the policy it will firstly checks whether the container has any resource limits defined. After that, the policy verifies that the resource limit specified in the container is within the permissible range set by the maximum limit specified in the policy settings. If the container's resource limit exceeds the predefined maximum, the policy intervenes by allowing the user to mutate the container's settings, adjusting the limit to comply with the maximum value established in the policy configuration.

Great! This is exactly what we need Thanks

**Comment by jvanz** [comment]
Let me share a more format policy description:

## Description
This policy is designed to enforce constraints on the CPU and memory resource limits of Kubernetes containers. It follows a two-step verification process: initially checking whether the container has defined resource limits, and subsequently ensuring that these limits fall within the permissible range set by the maximum limits configured in the policy settings.

## Configuration
Users can configure the policy using the following parameters in YAML format:

```yaml
# optional - the maximum permissible CPU limit
maxCPULimit: "2"
# optional - the maximum permissible memory limit
maxMemoryLimit: "4G"
```

Both CPU and memory limits should be expressed using the [quantity definitions](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) of Kubernetes.

## Constraints
The policy assumes that users have defined both CPU and memory resource limits for their containers. If the specified CPU or memory limit exceeds the maximum permissible limit configured in the policy, the policy will intervene to mutate the container's settings. It adjusts the limit to comply with the configured maximum values.

## Possible Scenarios
This policy operates as follows:

| Scenario                 | Configuration                        | Outcome                                                                                                              |
|--------------------------|--------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| Limits Within Range      | `maxCPULimit: "2"`<br>`maxMemoryLimit: "4G"` | Container settings accepted without modification if both CPU and memory limits are defined within permissible ranges.  |
| Exceeds Permissible Max  | `maxCPULimit: "2"`<br>`maxMemoryLimit: "4G"` | Policy intervenes if either CPU or memory limit exceeds predefined maximums. Mutates container settings to comply.      |
| Undefined Limit          | `maxCPULimit: "2"`<br>`maxMemoryLimit: "4G"` | Policy may take action if either CPU or memory limit is undefined (specific action not defined in provided description).|

**Comment by jvanz** [comment]
@elenagarciam do you want to perform this validations on init and ephemeral containers as well?

**Comment by elenagarciam** [comment]
Hi actually we are more worried about request enforcement than limit ones. As the real problem is that if users don't configure request, they are set with the limits value. Which turns out of a huge amount of reserved resources but not used. For init and ephemeral containers we have not detected issues to resolve

**Comment by flavio** [comment]
While reviewing @jvanz implementation of the policy, I realized there are many cases to keep in mind.

I've written the all the scenarios and their outcomes below, please take a look at them and provide your feedback. I hope I didn't miss anything.

# Container has request and limit set

No action from the policy. Request object is approved without changes.

# Container has no request and no limit set

Container request value:

  - If policy has request set: use it.
  - If policy does not have request set, but has a limit set: use the limit to express the request.
  - If policy does not have request and does not have limit set: do nothing
  
Container limit value:

  - If policy has limit set: use it.
  - If policy does not have limit set, but has request set: use request value to express limit
  - If policy does not have limit set and has no request set: do nothing
  

# Container has no request set, but has limits set

Container request value:

  - If policy has request set:
    - If policy's request value major than container limits: use container limits
    - Else: use policy request value
  - If policy does not have request set: use container limit value

Container limit value:

  - It doesn't matter whether the policy has limits set or not. The one specified by the container are used.


# Container has request set, but has no limits set

Container request value:

  - Container request value is always used

Container limit value:

  - If policy limit is set:
    - If policy limit major than container request value: use policy limit
    - Else: use the container request value as limit
  - If policy limit is not set: use container request value as limit

**Comment by jvanz** [comment]
@elenagarciam what do you think about the proposed changes in the policy behaivour [here](https://github.com/kubewarden/kubewarden-controller/issues/590#issuecomment-1892609129)?

**Comment by jvanz** [comment]
I've updated the PR implementing the suggested  changes in the previous [comment](https://github.com/kubewarden/kubewarden-controller/issues/590#issuecomment-1892609129) from @flavio.

**Comment by elenagarciam** [comment]
> @elenagarciam what do you think about the proposed changes in the policy behaivour [here](https://github.com/kubewarden/kubewarden-controller/issues/590#issuecomment-1892609129)?

Yes that configuration can work, when would the policy available?

**Comment by jvanz** [comment]
> Yes that configuration can work, when would the policy available?

The policy is released! 
https://artifacthub.io/packages/kubewarden/container-resources/container-resources

Let us know if you miss something. If there is no changes necessary, We'll bump it to version `0.1.0`. (it's `0.1.0-rc1` now)

**Comment by elenagarciam** [comment]
> > Yes that configuration can work, when would the policy available?
> 
> @elenagarciam The policy is released! https://artifacthub.io/packages/kubewarden/container-resources/container-resources
> 
> Let us know if you miss something. If there is no changes necessary, We'll bump it to version `0.1.0`. (it's `0.1.0-rc1` now)

Actually I was testing it, I have one question, 
Do I need to create another policy server o can I use the default one?

**Comment by jvanz** [comment]
> Actually I was testing it, I have one question, Do I need to create another policy server o can I use the default one?

You can deploy the policy in any policy server.

**Comment by jvanz** [comment]
@elenagarciam We've just released another version of the policy with a quick fix for rancher UI and fix for mutating policies. Let us know what you experience using it. Thanks!
