### ISSUE TITLE
New policy: share host PID namespace

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#598]
## Description

By default, containers running in the same Pod have dedicated PID namespaces. That means they cannot see each other processes.

It's however possible to disable this isolation feature inside of a Pod. This is done by setting this value of the pod spec to true:

```yaml
spec:
  shareProcessNamespace: true
```

More details [here](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/).

The purpose of this policy is to deny the creation of Pods that have this attribute enabled.

## Configuration

No configuration value

## Note

It's probably faster to implement this policy using Rego

**Comment by jvanz** [comment]
This policy has been released at Artifact hub:  https://artifacthub.io/packages/kubewarden/share-pid-namespace/share-pid-namespace-policy
