### ISSUE TITLE
Consider adding metrics

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#6]
Consider what metrics could be exposed on the controller, given that many of these metrics could just be retrieved by querying the API server (e.g. number of admission policies...), however it could be interesting to expose them directly in a dedicated endpoint.

# Why this is needed

Users can leverage tools like Prometheus to scrape these metrics and then:
* Plot statistics about the controller (eg: memory/cpu used)
* Set alerts when something bad happens (eg: no instances running, all instances slowed down)

This can also help users to better define the deployment details of the controller (number of replicas, resource limits,...)

**Comment by rakshitgondwal** [comment]
Hey @ereslibre! I would like to work on this! Can you guide me on how should I tackle this?

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers, I'm thinking about this issue. I'm not sure if we need a new endpoint. We already have an integration with [OpenTelemetry](https://opentelemetry.io/). I think we can expand and use it to expose this metrics. Maybe we can add a background job to compute these metrics and write them into OpenTelemetry.  What do you think?

**Comment by flavio** [comment]
I think nodeexporter is already providing the metrics about cpu/memory usage. I honestly don't know what else we could add right now.

Unless we have some concrete examples I would close this issue

**Comment by jvanz** [comment]
> I think nodeexporter is already providing the metrics about cpu/memory usage. I honestly don't know what else we could add right now.

@rakshitgondwal can you double check this info?
