### ISSUE TITLE
Release Community Meeting recording

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#601]
We should upload the recording of December on our youtube channel

Required:
- [x] Fix December recording name - it was released under name `Community Meeting October`
- [x] Add descriptions to videos in Kubewarden playlist

Would be nice:
- [x] Reorder recordings according to months
- [x] Play newest recording automatically when I open [Kubewarden playlist](https://www.youtube.com/@Rancher/playlists)

CC @robertsirc

**Comment by robertsirc** [comment]
This is done @flavio

**Comment by viccuad** [comment]
The latest video for Jan 2024 can be downloaded from:
https://zoom.us/rec/play/g8jPZn9LP-tTo5HfBrczjiq1lAYiu3Wa-4gCzjcH1s3zhsLfJn3YVPwbwdkoleA398fxFtYBncvGcgU.FS3yqaLTPvVMftpG

The video descriptions can be copy-pasted from:
https://docs.google.com/document/d/1H_CFkcnmNdodIex0pSfSZOBeAUzXNmN4cm7N7DCLqWk/edit?usp=sharing

**Comment by robertsirc** [comment]
i dont have access to this doc

**Comment by robertsirc** [comment]
@flavio I finished this but I cannot close out the task assigned to me.

**Comment by kravciak** [comment]
This is done, thanks Robert
Recording are hosted here: https://www.youtube.com/playlist?list=PLfAoTEAPazb6D_TBWZAWZtAnIbK6b7GTi
