### ISSUE TITLE
[Backport 2.7] k8s 1.27 chart support 

### ISSUE THREAD

**Issue by MKlimuszka** [kubewarden/kubewarden-controller#613]
### Solution you'd like

Backport of https://github.com/kubewarden/kubewarden-controller/issues/465

**Comment by viccuad** [comment]
Hi @MKlimuszka, I'm not sure I understand exactly what is the desired backport. Can you expand a bit?
Is it mean for backporting the support of k8s 1.27 into the Kubewarden release shipped in Rancher 2.7?

Thankfully, Kubewarden doesn't need anything specific to support k8s 1.27, and we already advertise we support it with the proper annotation in the last releases:
https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/Chart.yaml#L44
