### ISSUE TITLE
Emit Kubernetes events for policy status change

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#616]
This comes from https://www.youtube.com/watch?v=KbKQu3AqhBY.

Currently only tracing and monitoring give insights on Kubewarden policy state. 

Policies have status (unscheduled, pending, active). But that that if policies are already deployed and active in a policy-server, scheduling a change of them (for rules, settings, etc), would not move back to pending and again to active. Since the old instantiated policy is still reachable via the webhook and the old policy-server pod. This can be confusing in UI and for new users.

### Acceptance criteria

- Emit Kubernetes events when policies change the status (to unscheduleded, pending, to active).
- Consider emitting a specific event when a policy is already active yet is being updated (with new rules, settings, etc).
- Add integration tests for the events.

**Comment by viccuad** [comment]
Having events would help downstream (such as Kubewarden UI) in checking against them, instead of only looking at state. Amelioriating things like https://github.com/rancher/kubewarden-ui/issues/543.

**Comment by flavio** [comment]
Closing for now. We didn't get any request about this feature from the actual users of KW and we have more pressing things to do. We can come back to this issue based on community feedback
