### ISSUE TITLE
kubewarden-controller: enable codecov

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#623]
Our unit test should emit information about the code coverage of our codebase. The coverage will then be used by CodeCov.

## Acceptance criteria:

* Enable CodeCov bot on the repository

**Comment by viccuad** [comment]
Performed evaluation of Codecov.
Docs:
- https://docs.codecov.com/docs/github-tutorial
- https://docs.codecov.com/docs/common-recipe-list

Codecov works by running the language code coverage tool, and uploading the results to the Codecov SaSS by using their own `codecov` cli utility. It's free for Open Source repos.
When uploading, one can "flag" different coverage reports to bundle or treat them with different rules. Example: a mature backend that should be well tested and a younger frontend which is allowed to have less tests.

For us, that means separating the unit-tests and integration-tests.

Codecov needs a GH Application enabled for the GH organization, so it can read the repos and write commit statuses and PRs.

Opened https://github.com/kubewarden/kubewarden-controller/pull/631.
