### ISSUE TITLE
Integration tests are flaky

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#653]
Recently we notice that the integration tests are flaky and failing time to time. With no reason related to the code changes. It's looks like that we have some timeout problems. This is an example:

https://github.com/kubewarden/kubewarden-controller/actions/runs/8007800052/job/21882884521

### Acceptance criteria
- Checks why the tests are failing in our CI and fix it.

**Comment by viccuad** [comment]
Duplicated, closing in favour of https://github.com/kubewarden/kubewarden-controller/issues/628
