### ISSUE TITLE
[Spike] Feature Request: allow operators to provide custom rejection message

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#655]
### Is your feature request related to a problem?

As an operator, I would like to give more context to my users when an operation is rejected by a Kubewarden policy.
For example, I would like to point the users to an internal WIKI where the error message is explained and the remediation paths are illustrated.

Currently, the rejection message originated by a policy is the one hard coded by the policy author.

### Solution you'd like

When deploying a policy, have a way to define an additional error message to be reported back to the user. Maybe this could be set on the ClusterAdmissionPolicy/Admission Policy CRD

### Anything else?

Technically speaking, we could add the user defined messages as `Warnings` inside of the `AdmissionResponse` object.

See [here](https://github.com/kubernetes/kubernetes/blob/331ced5606fe32d8beb77c974b28dc12f7795012/pkg/apis/admission/types.go#L146)

**Comment by viccuad** [comment]
Added to 1.16 milestone. Should be refined for 1.17.

**Comment by viccuad** [comment]
Cluster operators may want to provide a more specific rejection message than
those provided by the policy author.

The rejection message from the cluster operator should have more priority than
the ones from the policy author, as some policies may need recompilation for
their messages to change.

### Acceptance criteria

- Add a new `spec.message` to (Cluster)AdmissionPolicies, optional, that expects a string.
  If provided, this new field will specify the message used when the policy
  performs a rejection. This substitutes the original rejection message provided
  by the policy (usually hardcoded). The original rejection message will be
  available as part of the `Warnings` inside of the `AdmissionResponse` object.

### Considerations

Both Rego and CEL already support custom rejection messages via `deny[msg] {
msg }`
([example](https://docs.kubewarden.io/next/tutorials/writing-policies/rego/open-policy-agent/create-policy#the-policy)),
and `validations[ {expression, messageExpression}]`
([example](https://docs.kubewarden.io/tutorials/writing-policies/CEL/reusing-vap)). Yet Rego policies need recompilation.
Both of these messages will be part of the `Warnings` if the new `spec.message` is used.

PolicyGroups already have `spec.message`, and the per-member messages already are part of the `Warnings`.

For PolicyReports no changes are needed. The error message will end in the
PolicyReportResult spec.Description, as usual rejection messages do. We need to
schedule work to include the messages in `Warnings` into PolicyReportResults
nevertheless.

In the future, we could add a new `spec.messageExpression`, optional, that expects a CEL expression.

**Comment by flavio** [comment]
I like the proposal, to summarize:

- No changes to PolicyGroup policies
- New `message` field added to `(Cluster)AdmisisonPolicy`, plus the behavior about `warnings` describe above
- One day, if requested, introduce `messageExpression` that leverages CEL

**Comment by fabriziosestito** [comment]
the proposal LGTM

**Comment by jvanz** [comment]
LGTM as well.

**Comment by viccuad** [comment]
Opened https://github.com/kubewarden/kubewarden-controller/issues/879, closing this spike.
