### ISSUE TITLE
Remove `repo` repository

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#658]
While reviewing our repositories, I stumbled over the [`repo`](https://github.com/kubewarden/repo) repository.

This is something that, AFAIK, nobody is using.

If you're fine with that, I propose to remove the repository to reduce the noise.

Please leave your opinion below as a comment.

**Comment by flavio** [comment]
I'm fine with the removal of the repository

**Comment by jvanz** [comment]
I'm also think we can remove it.

**Comment by flavio** [comment]
moving to blocked, waiting for @viccuad to be back and express his opinion on the topic

**Comment by fabriziosestito** [comment]
👍

**Comment by viccuad** [comment]
I'm ok with removing it too.

**Comment by flavio** [comment]
Thanks, I'm  going to do that
