### ISSUE TITLE
Configure codevoc to ignore some files and add missing packages.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#661]
We are in the process to improve the Kubewarden controller test coverage. To make the metric more reliable, we need to configure codecov to ignore some files. These files constits on files that are generated by some tool or store static data where does not make sense to test. These files are:

- pkg/apis/policies/v1/zz_generated.deepcopy.go
- pkg/apis/policies/v1alpha2/zz_generated.deepcopy.go
- internal/pkg/constants
- pkg/apis/policies/v1alpha2

The `internal/pkg/constants` and `pkg/apis/policies/v1alpha2`do not show up in the report already. However, I'm not sure if this is due the right reasons. This bring the second goal of this tasks. Some packages are not shown in the report:

- internal/pkg/admissionregistration
- internal/pkg/metrics
- internal/pkg/naming
- pkg/apis/policies/v1alpha2 

We must understand why this is happening and fix it.

### Acceptance criteria
- [x] Configure codecov to ignore the files listed previously that are generated by tools and where testing does not make sense. 
- [x] Add missing packages in the code coverage report

This is a spin off from https://github.com/kubewarden/kubewarden-controller/issues/648

**Comment by fabriziosestito** [comment]
> The internal/pkg/constants and pkg/apis/policies/v1alpha2do not show up in the report already. However, I'm not sure if this is due the right reasons. This bring the second goal of this tasks. Some packages are not shown in the report:
> 
>     internal/pkg/admissionregistration
>     internal/pkg/metrics
>     internal/pkg/naming
>     pkg/apis/policies/v1alpha2
These packages do not show because they don't have tests
