### ISSUE TITLE
Refactor the `internal/pkg/admissionregistration` package

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#664]
The  `/internal/pkg/admissionregistration` package is used by the controller to generate the CA and certificates. But it  has a misleading name and the tests for it is minimal. I think we should refactor this package renaming it and maybe bring the changes from the [feat-ca-changes](https://github.com/kubewarden/kubewarden-controller/tree/2d8d73e405ff18937e9457d86159e1fb5f258ffe/internal/pkg/certificates) branch into main. 

As the code in the branch already have tests, this will help us in our goal to reach 70% code coverage. Plus, its  name make more sense. Furthermore, we advance a little bit in the path of removing cert-manager. However,  this is **not** the main reason for this change here.

**Comment by fabriziosestito** [comment]
@jvanz could you elaborate a bit more on which changes you are proposing to bring from the ca changes feature branch?

**Comment by jvanz** [comment]
> @jvanz could you elaborate a bit more on which changes you are proposing to bring from the ca changes feature branch?

I was thinking of coping the [certificates](https://github.com/kubewarden/kubewarden-controller/tree/2d8d73e405ff18937e9457d86159e1fb5f258ffe/internal/pkg/certificates) package from the branch, which is basically a copy of the `admissionregistration` package with better names and tests, into main branch. Updating the references to the `admissionregistration` package in the `admission`  and using the new `certificates` package.  We may use the `admission` package from the feature branch to as [example](https://github.com/kubewarden/kubewarden-controller/blob/2d8d73e405ff18937e9457d86159e1fb5f258ffe/internal/pkg/admission/policy-server-ca-secret.go#L57-L61) of how to do it. But we just need to leave the code used to get and generate the root CA created by the controller out .

**Comment by jvanz** [comment]
This is has been done at #777
