### ISSUE TITLE
review usage of `taiki-e/install-action`

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#667]
The kwctl and the policy-server projects are making use of https://github.com/taiki-e/install-action

Do we actually need this action? We already have our custom GH actions that deal with installing some special packages.

The goal should be to keep the number of GH actions we use to the minimum, for security reasons.

## Acceptance criteria

* [x] Identify all the projects that are using this GH action
* [x] Understand if this action is really needed
* [x] Eventually, replace this GH action with something owned by us

**Comment by jvanz** [comment]
This github actions is used in all of [our major rust repositories](https://github.com/search?q=org%3Akubewarden%20taiki-e%2Finstall-action&type=code): policy-server, kwctl, policy-evaluator and policy-fetcher.  It's used to install `cargo-tarpaulin`.
