### ISSUE TITLE
Release Community meeting recording (March)

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#681]
## Acceptance criteria

- [x] Upload the recording on our youtube channel
- To double check:
  - [x] Recording is ordered (should be last one)
  - [x] Recording has description

## Description:

This meeting’s agenda:

```
 - Upcoming 1.11 release
   - Audit scanner improvements: memory consumption, parallelization
   - Performance improvement of policies doing host calls
   - New OCI host capability
 - KubeCon EU
 - Update to the [container-resources policy](https://artifacthub.io/packages/kubewarden/container-resources/container-resources)
 - Code coverage improvements
 - 1.12 - when and what are aiming for
```

## Recording

https://zoom.us/rec/share/WpCIkxKQEBbdpFY4s4xb08wTeu7_w7NqWqeO-7_ML0sg8C78qsuC8ZwQQy2kU3BM.etuD0OuSsJLE_WNU?startTime=1710435906000

**Comment by robertsirc** [comment]
It is uploaded and processing right now. I will correct the order once it is done processing.
