### ISSUE TITLE
Move Governance, license, contribution guidelines and ADOPTERS files inside of the `community` repository

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#685]
As described in the this https://github.com/kubewarden/kubewarden-controller/issues/659, we are in the process of creating the community repository. This central repository should serve as a central location for contributors, security researchers, and other interested parties to discover and under the project through GitHub. This include moving important files into it. Wich includes: Governance, license, contribution guidelines and adopters files. 

### Acceptance criteria

- [x] Move Governance, license, contribution guidelines and ADOPTERS files inside of the community repository.
- [x] Amend docs.kubewarden.io to point to them instead of previous versions where relevant. https://github.com/kubewarden/docs/pull/383
- [x] Amend kubewarden.io survey link to ADOPTERS file.
- [x] Remove old versions from previous repos.

**Comment by viccuad** [comment]
Reopening, still things to do.

**Comment by jvanz** [comment]
As far as I can see, this is done. Closing issue
