### ISSUE TITLE
Audit Scanner overloading a single pod from policy server

### ISSUE THREAD

**Issue by brunorene** [kubewarden/kubewarden-controller#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed that when Audit Scanner starts to run all request load is targetted into a single policy server pod, instead of being spread out throughout all available replicas, making the pod struggle to respond to all Audit scanner requests and making the auditing process take much longer. It does seem that Audit scanner also has very little concurrency when validating resources. I tried it on a large cluster (thousands of namespaces) and at the moment is taking around 2 days to finish.

### Expected Behavior

Audit Scanner should take advantage of all replicas available from policy server to spread the request load

### Environment

```markdown
- OS: Linux
- Architecture: amd64
```

**Comment by flavio** [comment]
Closing, this is now fixed with the 1.13 release
