### ISSUE TITLE
Feature Request: Ability to configure limits and requests of CPU/Memory on PolicyServer CRD

### ISSUE THREAD

**Issue by brunorene** [kubewarden/kubewarden-controller#710]
### Is your feature request related to a problem?

Yes at the moment we need to create a LimitRange resource to limit memory for the policy server deployment.

### Solution you'd like

The PolicyServer CRD would have a block to configure limits and requests for CPU and memory for the policy server deployment and also be able to configure it through kubewarden-defaults Helm Chart.

### Alternatives you've considered

At the moment we are using LimitRange but it applies to all the namespace so it is not a very good solution.

### Anything else?

Not really thanks

**Comment by viccuad** [comment]
Skipping exposing this new features through Rancher UI, see https://github.com/kubewarden/helm-charts/issues/418.

With that, this is done, will get shipped on the next release.
