### ISSUE TITLE
Feature Request: expose webhook `matchConditions`

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#758]
### Is your feature request related to a problem?

Starting from kubernetes 1.26, CEL support has been added into Kubernetes. On top of [`ValidatingAdmissionPolicy`](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) the `ValidatingWebhookConfiguration` and the `MutatingWebhookConfiguration` CRDs obtained a new field: `matchConditions`.

The `matchConditions` field allows to specify a list of CEL expressions that are used to determine whether the webhook endpoint should be called or not.

This is extremely powerful, since it allows to do something like "do not call this webhook endpoint if `!object.spec.containers[0].image.startsWith("registry.local.lan")`.

More information can be found [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions).

### Solution you'd like

The `AdmissionPolicy` and the `ClusterAdmissionPolicy` CRDs should be updated to feature a `matchConditions` field.

The kubewarden-controller should then propagate them into the `(Validating|Mutating)WebhookConfiguration)` objects.

### Anything else?

The `matchConditions` field has been introduced starting with Kubernetes 1.27 (see [here](https://v1-27.docs.kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/)).

Currently (Jun 2024), Kubernetes 1.26 has been [EOL](https://endoflife.date/kubernetes) for ~ 3 months. That means all the maintained Kubernetes versions have this feature available behind a feature gate:

> Note: Use of matchConditions requires the [featuregate](https://v1-27.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)AdmissionWebhookMatchConditions to be explicitly enabled on the kube-apiserver before this feature can be used.

Starting from Kubernetes 1.30 the feature gate is gone, since this feature graduated to stable.

I think our CRDs should always have the `matchConditions` field. We have to figure out what the controller should do when running on Kubernetes >= 1.27 < 1.30 and the `AdmissionWebhookMatchConditions` feature gate is disabled.

I suspect in this condition the `(Validating|Mutating)WebhookConfiguration` resources would still have this field, but it would not have any effect. I hope that's the case, because it would allow our controller to always propagate the `matchConditions` field, without having to perform any kind of check.

I would not consider the use case of propagating `matchConditions` on a Kubernetes cluster <= 1.26 since they are all EOL. We can update our docs/helm charts to require Kubernetes >= 1.27

**Comment by viccuad** [comment]
> I suspect in this condition the (Validating|Mutating)WebhookConfiguration resources would still have this field, but it would not have any effect. I hope that's the case

Sadly, we can't set matchCOnditions On Kubernetes <= 1.25 or those without the feature gate enabled:

```
# validatingwebhookconfigurations.admissionregistration.k8s.io "clusterwide-no-privileged-pod" was not valid:
# * patch: Invalid value: "map[]": strict decoding error: unknown field "webhooks[0].matchConditions"
```

I suppose this reduces all cases to the same case of what the controller should do when running on Kubernetes >= 1.27 < 1.30 and the AdmissionWebhookMatchConditions feature gate is disabled or unexistent.

**Comment by flavio** [comment]
I did some searches, you can use the [`DiscoveryClient`](https://pkg.go.dev/k8s.io/client-go/discovery) to obtain the openAPI spec supported by the k8s server.

The idea is to obtain the spec of `io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration` and look at the fields it offers.

Basically do the equivalent of:

```console
kubectl get --raw /openapi/v2 | jq '.definitions["io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration"]'
```

**Comment by viccuad** [comment]
To close, we need:
- [ ] controller & CRD changes https://github.com/kubewarden/kubewarden-controller/pull/813
- [ ] Consume reference CRD-docs-for-docs.md into kubewarden/docs
- [x] Consume CRDs into helm-charts (automated)
- [ ] Update docs

**Comment by viccuad** [comment]
Moving to blocked, and adding https://github.com/kubewarden/kubewarden-controller/issues/815 to the TODO.
