### ISSUE TITLE
Release Community meeting recording (June)

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#767]
## Acceptance criteria

- [x] Upload the recording on our youtube channel
- To double check:
  - [x] Recording is ordered (should be last one)
  - [x] Recording has description

## Description:

This meeting’s agenda:

```
This meeting’s agenda:
- 1.13 release
  * Reduced PolicyServer memory usage
  * Controller improvements
  * Audit Scanner request improvements 
- CEL policy
- What’s coming next:
  * Group policies
  * 1.14
```

## Recording

https://zoom.us/rec/play/NhQGWH29unZ6RaoU3A5HDF7Mi7TTNe3Cm1hXNWfNGaTvc8UlQQCMlnjoHlnaS6tDolljp9WE6JThvr5m.crz6JVFz_pC-FAEl?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FUTo3pPC6BSOMj9Qh3QMSWxs6VImgesAbZrb_NcFICRDzYBrDRicglIoK7gg0d3Dr.JKXaimUPvAXcVx6z

**Comment by robertsirc** [comment]
Sorry for the delay doing this now.

**Comment by robertsirc** [comment]
This is uploading now should be done.
