### ISSUE TITLE
Uniform golangci configuration across all repositories

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#778]
### Description

We need to uniform the golangci configuration across all repositories.
An idea could be using an opinionated configuration, such as: https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322, which is actvitely maintained and it is used by: 

https://github.com/spinkube/runtime-class-manager/blob/main/.golangci.yaml

This also means putting some extra effort to make the linters happy.

**Comment by flavio** [comment]
I'm in favor of doing that. :+1:
