### ISSUE TITLE
Weaveworks rego policies: create a migration script

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#805]
### Is your feature request related to a problem?

Based on the output of this spike: https://github.com/kubewarden/kubewarden-controller/issues/766 we need to create a migration script to convert the policies in the [weaveworks policy library](https://github.com/weaveworks/policy-library), focusing on the policies that include unit tests.

### Solution you'd like

Weaveworks uses the docker image `weaveworks/polctl` for automation on auto-generating, testing, documenting, and releasing the policies, [repo](https://github.com/weaveworks/polctl) here.

The repo uses `openpolicyagent/opa` to test the policies. Since we already use `opa` to build as a wasm target, I find it a good compromise to keep that workflow.

Weavework policies are marked with `spec.standards`. The list of available standards are in `./standards`
([example](https://github.com/search?q=repo%3Aweaveworks%2Fpolicy-library%20weave.controls.cis-benchmark.5.7.4&type=code)), and the policies have `spec.standards`. For now, transform these into `metadata.annotations`.

The policies are Rego gatekeeper policies.

## Acceptance criteria

The end result is a forked monorepo with the following format:

```
$ tree
.
├── LICENSE
├── artifacthub-repo.yml
├── policy1/
│       ├── README.md
│       ├── tests/
|       │   └── deployment.yaml
│       ├── policy.rego
│       ├── Makefile
│       ├── metadata.yml
│       └── artifacthub-pkg.yml
└── policy2/
    ...
```

Example for one policy in https://github.com/viccuad/rego-policies.

For that:

- [x] Per policy in `examples/,policies/`, do a 1-time conversion:

  - [x] Reuse our OPA Rego `Makefile` from [disallow-service-loadbalander-policy](https://github.com/kubewarden/disallow-service-loadbalancer-policy). Should be
        adapted to run rego tests with `opa` from `./tests`. Not all policies have a
        `./tests/policy_test.rego`.
  - [x] Compile a `README.md` from `policy.yaml`, by reusing the following fields in a template:
    - [x] `metadata.name` with `weave.policies` prefix removed.
    - [x] `spec.name`, `description`, `how_to_solve`, `tags`.
  - [x] Compile a `metadata.yml` from `policy.yaml`, by reusing the following fields from the Weaveworks policy:
    - [x] `spec.id`, without the prefix `weave.policies` as `io.kubewarden.policy.title`
    - [x] `io.kubewarden.policy.ociUrl:  ghcr.io/kubewarden/policies/<id>`
    - [x] `io.kubewarden.policy.url: https://github.com/kubewarden/<id>`.
    - [x] `io.kubewarden.policy.url` and `io.kubewarden.policy.source` hardcoded to the Rego monorepo for these policies. (e.g: `https://github.com/kubewarden/rego-policies`).
    - [x] `spec.category` as annotations `io.kubewarden.policy.category`, without prefix `weave.category`
    - [x] `spec.category` as annotations `Best practices RBAC` for policies listed in `./goodpractices`
    - [x] `spec.severity` as annotations `io.kubewarden.policy.severity`
    - [x] `spec.targets` as annotations `io.artifacthub.resources`
    - [x] `spec.standards` as annotation `io.kubewarden.policy.standards`, where each
            element in the `controls` array is a new annotation, and it is commented out until we evaluate further. The list of available standards are in `./standards` ([example](https://github.com/search?q=repo%3Aweaveworks%2Fpolicy-library%20weave.controls.cis-benchmark.5.7.4&type=code)). Since annotations only allow 1 field and not an array, they can be concatenated for now.
    - [x] `spec.description` as annotation `io.kubewarden.policy.description`
    - [x] `spec.targets` into `rules` by computing the list of resources. This translation is not trivial.
  - [x] Adapt the `policy.rego`:
    - Use the same `package` for all rego files, including tests (e.g: `package policy`).
  - [x] Reuse `./tests/`, which will get run by the `make tests`
  - [x] `artifacthub-pkg.yml` following [artifacthub docs](https://artifacthub.io/docs/topics/repositories/kubewarden-policies/). Generated by our Makefile.

- Additional:
  - [x] Clarify if policy has `settings:` or `parameters:` key
  - [x] Try to run tests
  - [x] Ignore policies without tests
  - [x] Handle various prefixes: weave.policies, weave.templates, ...

- Weavework policies are marked with `spec.standards`. The list of available
  standards are in `./standards` ([example](https://github.com/search?q=repo%3Aweaveworks%2Fpolicy-library%20weave.controls.cis-benchmark.5.7.4&type=code)).
- Manually mark the converted policies with annotation
  `io.kubewarden.policy.category: Best practices RBAC` for those policies listed in
  from `./goodpractices`.
- CI & CD: I found no way to programatically create jobs. Hence the jobs will go through all repos when they are called.
  To release, for each policy folder, if no git tag matching the policy id and version, build and push the annotated-policy.wasm as usual.

### Unresolved

- Evaluate the `spec.standards`. For these to be valid, the data structure of the k8s deployment needs to match the expected lyout. (E.g: expecting users to deploy things segregated by namespaces, and is a specific way).
- Not all policies have rego tests. Skipping them could diminish the numbers greatly.

**Comment by viccuad** [comment]
As an example of a policy that has been migrated manually:
- from Weaveworks: https://github.com/weaveworks/policy-library/tree/main/policies/ControllerContainerBlockSSHPort
- Migrated: https://github.com/viccuad/rego-policies/tree/main/policies/ControllerContainerBlockSSHPort

**Comment by kravciak** [comment]
- clarify if policy has `settings:` or `parameters:` key

**Comment by viccuad** [comment]
When having another look at the policies we realized that some of them don't support `replicasets`  (e.g: replicaset is missing here) on all the [workload resources](https://kubernetes.io/docs/concepts/workloads/):
https://github.com/weaveworks/policy-library/blob/main/examples/ControllerAffinityNodeSelector/policy.rego#L41

This means we would need to edit the `policy.rego` so the policy supports `replicasets`, and then we would need to add replicasets to our `metadata.yml::rules`.

**Comment by flavio** [comment]
I think it's fine for a policy to support `ReplicaSet`, this is an intermediate CR that is rarely used in a direct fashion. Everybody operates at a higher level (like `Deployment`), hence don't go crazy extending the `.rego` files, just make sure our metadata doesn't mention `ReplicaSet`

**Comment by kravciak** [comment]
YAML tests are automatically passing if there is any rego test (I guess because they fail to load..)
I don't consider them reliable.

```bash
~ l input/policies/ControllerMissingKubernetesAppComponentLabel/tests/
total 8
-rw-r--r-- 1 kravciak users 1944 Dec 11 17:27 app_k8s_io_component_test.rego
-rw-r--r-- 1 kravciak users  386 Dec 11 17:27 test.yaml

~ ./test_policies --policy-path input/policies/ControllerMissingKubernetesAppComponentLabel
2024/12/12 11:37:23 Testing ControllerMissingKubernetesAppComponentLabel policy

~ mv  input/policies/ControllerMissingKubernetesAppComponentLabel/tests/app_k8s_io_component_test.rego ~

~ ./test_policies --policy-path input/policies/ControllerMissingKubernetesAppComponentLabel
2024/12/12 11:37:39 Testing ControllerMissingKubernetesAppComponentLabel policy
2024/12/12 11:37:39 Testing ControllerMissingKubernetesAppComponentLabel policy failed: [{"issue_detected":true,"msg":"Missing 'app.kubernetes.io/component' label","recommended_value":"app.kubernetes.io/component","violating_key":"metadata.labels"}]
```

**Comment by kravciak** [comment]
Migration script: https://github.com/kravciak/weave-migration/tree/main.
This is initial output, we need to check everything works as expected.

 - policies with `tests/*.rego` migrated to `output/policies/`
 - others migrated to `output/staging`
 - some policies yaml tests failing, but it seems like issue with their testing platform
 - policy `KubernetesProhibitKind` - rules are probably wrong, they should target everything
