### ISSUE TITLE
Bootstrap the root CA and the controller webhook server TLS certificate and remove the cert-manager dependency.

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#820]
We need to remove the `cert-manager` dependency.
Therefore, we need to bootstrap the root CA the first time the controller is installed and generate the controller's webhook TLS certificate.
Both the CA root and the controller webhook TLS certificate are stored in a secret.

This can be done directly in helm, by using the [genCa](https://helm.sh/docs/chart_template_guide/function_list/#genca) and [genSignedCert](https://helm.sh/docs/chart_template_guide/function_list/#gensignedcert) helper function.
Using helm is a good approach since it removes the complexity of bootstrapping certificates in the controller main function, which implies coordination with the leader election and generally slows down the initialization of the controller container.

See https://github.com/aquasecurity/aqua-helm/blob/d212befe175998b7d8a83a7b0a33080993f171e5/kube-enforcer/templates/auto-generate-tls.yaml as an example

Subtasks:
- generate the CA certificate and the TLS cert. This must be done just once when the controller chart is installed, by using the [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function)  function.
- inject the CA certificate into the Validating/Mutating webhook configuration directly in the helm chart
- remove the policy server CA secret creation in the reconciliation loop. Use the CA from the helm initialized secret instead.
- remove cert-manager dependency from the helm chart and the controller

**Comment by viccuad** [comment]
Closing as done, the only part missing is "remove cert-manager dependency from the helm chart and the controller" and that's tracked on https://github.com/kubewarden/kubewarden-controller/issues/7.
