### ISSUE TITLE
Extend CRD and add matchConditions (optional).

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#858]

**Comment by flavio** [comment]
TODO: double check the current code, there's a high chance this is already done

**Comment by jvanz** [comment]
This change is not required. The policy group types [already have](https://github.com/kubewarden/kubewarden-controller/blob/ecfb764b90588a0163e0efa8d86fef22e780c474/api/policies/v1/policy_types.go#L241-L254) the `MatchConditions` field. Both [`AdmissionPolicyGroup` ](https://github.com/kubewarden/kubewarden-controller/blob/ecfb764b90588a0163e0efa8d86fef22e780c474/api/policies/v1/admissionpolicygroup_types.go#L27) and [`ClusterAdmissionPolicyGroup`](https://github.com/kubewarden/kubewarden-controller/blob/ecfb764b90588a0163e0efa8d86fef22e780c474/api/policies/v1/clusteradmissionpolicygroup_types.go#L27) uses the `PolicyGroupSpec` with the `MatchConditions` field.
