### ISSUE TITLE
Add E2E test for upgrade case, cert rotation

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#864]
### Acceptance criteria

- Remove cert-manager from usual install tests: this is done to done once 1.17 is released, otherwise the 1.16 -> 1.17 upgrade test won't work, since 1.16 requires cert-manager to be installed
- ~~Add new test for upgrading from 1.16 (previous cert-manager) to 1.17 (self-rotation).~~: Update the current e2e upgrade test already cover this scenario. There's no additional work to be done

**Comment by flavio** [comment]
assigned to 1.18, see the explanation of the only action to implement

**Comment by kravciak** [comment]
Cert-manager is now [installed](https://github.com/kubewarden/kubewarden-end-to-end-tests/blob/main/scripts/helmer.sh#L110) only if kubewarden <= 1.16 and [removed](https://github.com/kubewarden/kubewarden-end-to-end-tests/blob/main/scripts/helmer.sh#L144) after upgrade to 1.17.
