### ISSUE TITLE
SPIKE: Ensure SLSA lvl 3 for policies

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#910]
### Acceptance criteria

1. Make sure SLSA Lvl 3 is needed.
2. Implement if so.
3. Understand and document how many changes are needed to kubewarden/github-actions reusable workflows, as refactoring these means changing the build and release process of our policy repositories.

**Comment by viccuad** [comment]
To achieve this card we need:

## Add `permissions.attestations: write` to all policy workflows

This is so they can use the attestations on the reusable workflows. E.g: [here](https://github.com/kubewarden/verify-image-signatures/blob/main/.github/workflows/release.yml#L23).

## All the workflows and GHA need to be uniquely identified

This is done by digest pinning of the versions of GH actions. We can achieve this for 3rd party actions. For our own actions in kubewarden/github-actions, it isn't as easy.

Problem is, that all the GH actions that we use should have the
correct digest pinned before we tag. This is impossible as we can't
know the commit sha that the release should point to because it would
be the commit that changes the release pointers on the actions.

Using  branches for release management
https://docs.github.com/en/actions/sharing-automations/creating-actions/about-custom-actions#using-a-commits-sha-for-release-management
solves the problem partially. Yet I wonder how renovatebot behaves,
as I think it would try to continuously update the pin of the GHA by
opening PRs. The moment one merges the PR into the branch, renovatebot
would open PRs to update the pins again.

One solution here would be to not reuse actions, and only provide flattened reusable workflows.

Note: some GHA are not consuming checked binaries. For example, the "Install tinygo" step that downloads tinygo, which is provided as-si without signatures.

## The build artifact (`annotated-policy.wasm`) needs to be uniquely identified

Ideally, we would create the provenance for the specific artifact on the same job (VM) without needing to pass artifacts between jobs or workflows.

Doing it via signature or checksum may not be enough as we can't ascertain the chain when passing the signature or checksum and we may be open to timing attacks.

## To upload the provenance attestation, we must have already the digest of the pushed policy to the OCI repo.

This can be done with a refactor, since `kwctl push` prints the digest.

**Comment by flavio** [comment]
Thanks for the research, we need to spend some time discussing how to move forward with that. It's nice to know we don't have to make all our policies SLSA L3 yet

**Comment by viccuad** [comment]
I'm closing the spike as done.
